name             'chef_kafka'
maintainer       'Raintank, Inc.'
maintainer_email 'cookbooks@raintank.io'
license          'Apache 2.0'
description      'Installs/Configures chef_kafka'
long_description 'Installs/Configures chef_kafka'
version          '0.1.2'

depends 'chef_base', '~> 0.1.7'
depends 'java', '~> 1.40.0'
depends 'kafka', '~> 2.0.2'
depends 'lvm', '~> 1.3.6'
depends 'chef_zookeeper', '~> 0.1.0'
